// <auto-generated />
using System;
using Agppa.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agppa.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424153510_GamesTeamsAthletesStats")]
    partial class GamesTeamsAthletesStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Agppa.Api.Models.Athlete", b =>
                {
                    b.Property<int>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("athlete_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AthleteId"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Position")
                        .HasColumnType("longtext")
                        .HasColumnName("position");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("AthleteId")
                        .HasName("pk_athletes");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_athletes_team_id");

                    b.ToTable("athletes", (string)null);
                });

            modelBuilder.Entity("Agppa.Api.Models.AthleteGameStat", b =>
                {
                    b.Property<int>("AthleteGameStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("athlete_game_stat_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AthleteGameStatId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasColumnName("assists");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int")
                        .HasColumnName("athlete_id");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Rebounds")
                        .HasColumnType("int")
                        .HasColumnName("rebounds");

                    b.HasKey("AthleteGameStatId")
                        .HasName("pk_athlete_game_stats");

                    b.HasIndex("AthleteId")
                        .HasDatabaseName("ix_athlete_game_stats_athlete_id");

                    b.HasIndex("GameId", "AthleteId")
                        .IsUnique()
                        .HasDatabaseName("ix_athlete_game_stats_game_id_athlete_id");

                    b.ToTable("athlete_game_stats", (string)null);
                });

            modelBuilder.Entity("Agppa.Api.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("away_score");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int")
                        .HasColumnName("away_team_id");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("home_score");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int")
                        .HasColumnName("home_team_id");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("played_at");

                    b.HasKey("GameId")
                        .HasName("pk_games");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_games_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_games_home_team_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Agppa.Api.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("CoachName")
                        .HasColumnType("longtext")
                        .HasColumnName("coach_name");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("team_name");

                    b.HasKey("TeamId")
                        .HasName("pk_teams");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Agppa.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_users_team_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Agppa.Api.Models.Athlete", b =>
                {
                    b.HasOne("Agppa.Api.Models.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_athletes_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Agppa.Api.Models.AthleteGameStat", b =>
                {
                    b.HasOne("Agppa.Api.Models.Athlete", "Athlete")
                        .WithMany("GameStats")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_athlete_game_stats_athletes_athlete_id");

                    b.HasOne("Agppa.Api.Models.Game", "Game")
                        .WithMany("AthleteStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_athlete_game_stats_games_game_id");

                    b.Navigation("Athlete");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Agppa.Api.Models.Game", b =>
                {
                    b.HasOne("Agppa.Api.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_teams_away_team_id");

                    b.HasOne("Agppa.Api.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_teams_home_team_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("Agppa.Api.Models.User", b =>
                {
                    b.HasOne("Agppa.Api.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Agppa.Api.Models.Athlete", b =>
                {
                    b.Navigation("GameStats");
                });

            modelBuilder.Entity("Agppa.Api.Models.Game", b =>
                {
                    b.Navigation("AthleteStats");
                });

            modelBuilder.Entity("Agppa.Api.Models.Team", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
