@Agppa.Api_HostAddress = http://localhost:5039

### Teams
GET {{Agppa.Api_HostAddress}}/api/teams
Accept: application/json

###
### Athletes
GET {{Agppa.Api_HostAddress}}/api/athletes
Accept: application/json

###
